name: Build Extension
on: [ push ]
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm install --include=dev && npm run build

      - name: Sign and Release Firefox Extension
        if: contains(github.event.head_commit.message, '[release]')
        run: npm run sign-and-release
        env:
          WEB_EXT_API_KEY: "${{ secrets.MOZILLA_KEY }}"
          WEB_EXT_API_SECRET: "${{ secrets.MOZILLA_SECRET }}"

      - name: Create Stable Release
        if: contains(github.event.head_commit.message, '[release]')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable-latest"
          prerelease: true
          title: "Stable Development Build"
          files: |
            dist/artifacts/*

      - name: Create Development Release
        if: "!contains(github.event.head_commit.message, '[release]')"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/artifacts/*