name: Build Extension
on: [push]
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - run: npm install --global web-ext
      - uses: actions/checkout@master
      - run: web-ext build
