name: Build Extension
on: [push]
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - run: npm install --global web-ext
      - uses: actions/checkout@master
      - run: web-ext build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            web-ext-artifacts/*